# Netlify Configuration File

[build]
  # Directory to publish (where your static files are)
  publish = "."
  
  # No build command needed for static sites
  # command = ""

# Headers for better performance and security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "no-referrer-when-downgrade"

# Cache control for assets
[[headers]]
  for = "/styles.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/dashboard.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Redirects (optional - example)
# [[redirects]]
#   from = "/old-path"
#   to = "/new-path"
#   status = 301

# Environment variables (if needed)
# [build.environment]
#   MY_ENV_VAR = "value"

# Deploy contexts for different branches
[context.production]
  # Production-specific settings
  # command = ""

[context.deploy-preview]
  # Settings for deploy previews
  # command = ""

[context.branch-deploy]
  # Settings for branch deploys
  # command = ""